### ISSUE TITLE
pool-4-thread-1

### ISSUE THREAD

**Issue by mrpwes** [Alemiz112/StarGate#7]
```[01:13:31 INFO] [StarGate]: Registring Config
[01:13:31 INFO] [StarGate]: Registring StarGate Listener
[01:13:31 INFO] [StarGate]: Starting StarGate Protocol on Port: 47007
[01:13:31 INFO]: Enabled plugin StarGate version 1.2.5 by Alemiz
[01:13:31 INFO] [StarGate]: Done! StarGate Protocol is successfully running. Waiting for clients...
[01:13:32 INFO]: Listening on /0.0.0.0:19132
[01:14:07 INFO] [StarGate]: New client connected: lobby:123456789
[01:14:07 INFO] [StarGate]: ADDRESS: `myip`:46544
[01:14:08 INFO] [StarGate]: WARNING: Connection with lobby:123456789 has been closed!
[01:14:08 ERROR]: Exception in thread "pool-4-thread-1" java.lang.NumberFormatException: For input string: "lobby"
[01:14:08 ERROR]:       at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[01:14:08 ERROR]:       at java.base/java.lang.Long.parseLong(Long.java:692)
[01:14:08 ERROR]:       at java.base/java.lang.Long.valueOf(Long.java:1117)
[01:14:08 ERROR]:       at java.base/java.lang.Long.decode(Long.java:1268)
[01:14:08 ERROR]:       at alemiz.stargate.gate.Server.processPacket(Server.java:135)
[01:14:08 ERROR]:       at alemiz.stargate.gate.Handler.run(Handler.java:61)
[01:14:08 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[01:14:08 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[01:14:08 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:834)
```
I used the latest [StarGate-Atlantis](https://github.com/Alemiz112/StarGate-Atlantis) plugin

**Comment by mrpwes** [comment]
IF YOU ENCOUNTER THIS PROBLEM JUST Use latest from here https://jenkins.mizerak.eu/job/StarGate/
